"""Initial migration.

Revision ID: 444075b7d55e
Revises: 
Create Date: 2020-11-09 13:00:43.105154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444075b7d55e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'likes')
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
